DROP TABLE IF EXISTS activity_logs;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS claims;
DROP TABLE IF EXISTS qr_codes;
DROP TABLE IF EXISTS qr_batches;
DROP TABLE IF EXISTS weddings;
DROP TABLE IF EXISTS users;