CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password VARCHAR(200) NOT NULL,
  role ENUM('admin','host') NOT NULL DEFAULT 'host',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS weddings (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  name VARCHAR(160) NOT NULL,
  host_name VARCHAR(160) NOT NULL,
  event_date DATE NOT NULL,
  location VARCHAR(200) NOT NULL,
  amount_per_qr DECIMAL(10,2) NOT NULL DEFAULT 5.00,
  total_qr INT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_weddings_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS qr_batches (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  wedding_id INT UNSIGNED NOT NULL,
  total_generated INT UNSIGNED NOT NULL,
  amount_per_qr DECIMAL(10,2) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_qr_batches_wedding FOREIGN KEY (wedding_id) REFERENCES weddings(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS qr_codes (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  wedding_id INT UNSIGNED NOT NULL,
  token VARCHAR(64) NOT NULL UNIQUE,
  is_claimed TINYINT(1) NOT NULL DEFAULT 0,
  claimed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_qr_wedding (wedding_id),
  CONSTRAINT fk_qr_codes_wedding FOREIGN KEY (wedding_id) REFERENCES weddings(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS claims (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  qr_id INT UNSIGNED NOT NULL,
  wedding_id INT UNSIGNED NOT NULL,
  phone VARCHAR(40) NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  claimed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_claim_phone_wedding (phone, wedding_id),
  UNIQUE KEY uq_claim_qr (qr_id),
  CONSTRAINT fk_claims_qr FOREIGN KEY (qr_id) REFERENCES qr_codes(id) ON DELETE RESTRICT,
  CONSTRAINT fk_claims_wedding FOREIGN KEY (wedding_id) REFERENCES weddings(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payments (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  claim_id INT UNSIGNED NOT NULL,
  phone VARCHAR(40) NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  status ENUM('pending','success','failed') NOT NULL DEFAULT 'pending',
  transaction_ref VARCHAR(120) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_payments_claim FOREIGN KEY (claim_id) REFERENCES claims(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS activity_logs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NULL,
  action VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_activity_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);